/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("PoPrintObjectPageObjectPage journey");

        opaTest("Navigate to PoPrintObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            When.onThePoPrintListGenerated.onFilterBar().iExecuteSearch();
            Then.onThePoPrintListGenerated.onTable().iCheckRows();
            When.onThePoPrintListGenerated.onTable().iPressRow(0);

            Then.onThePoPrintObjectPageGenerated.iSeeThisPage();
        });

        opaTest("Check header actions of the Object Page", function (Given, When, Then) {
            Then.onThePoPrintObjectPageGenerated.onHeader().iCheckAction({ service: "com.sap.gateway.srvd.zui_mm_r002.v0001", action: "previewPdf", unbound: false }, { enabled: false });
            // When.onThePoPrintObjectPageGenerated.onHeader().iPressAction({ service: "com.sap.gateway.srvd.zui_mm_r002.v0001", action: "previewPdf", unbound: false });
            Then.onThePoPrintObjectPageGenerated.onHeader().iCheckAction({ service: "com.sap.gateway.srvd.zui_mm_r002.v0001", action: "confirmPrint", unbound: false }, { enabled: false });
            // When.onThePoPrintObjectPageGenerated.onHeader().iPressAction({ service: "com.sap.gateway.srvd.zui_mm_r002.v0001", action: "confirmPrint", unbound: false });
        });


        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});