/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("PoPrintListListReport journey");

        const defaultTableId = "";

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onThePoPrintListGenerated.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onThePoPrintListGenerated.onFilterBar().iCheckFilterField({ property: "ebeln" });
            Then.onThePoPrintListGenerated.onFilterBar().iCheckFilterField({ property: "bedat" });
            Then.onThePoPrintListGenerated.onFilterBar().iCheckFilterField({ property: "ekgrp" });
            Then.onThePoPrintListGenerated.onFilterBar().iCheckFilterField({ property: "lifnr" });
            Then.onThePoPrintListGenerated.onFilterBar().iCheckFilterField({ property: "ekorg" });
            Then.onThePoPrintListGenerated.onFilterBar().iCheckFilterField({ property: "werks" });
            Then.onThePoPrintListGenerated.onFilterBar().iCheckFilterField({ property: "noshow" });
        });

        // Note: this test will only work if the ListReport page has a search field and shows data that matches the search term. Please ensure that the test data and search term are set up accordingly.
        // opaTest("Perform a global search and check the result", function (Given, When, Then) {
        //     When.onThePoPrintListGenerated.onFilterBar().iChangeSearchField("Search Term");
        //     When.onThePoPrintListGenerated.onFilterBar().iExecuteSearch();
        //     Then.onThePoPrintListGenerated.onTable(defaultTableId).iCheckRows();
        //     When.onThePoPrintListGenerated.onFilterBar().iChangeSearchField(undefined);
        //     Then.onThePoPrintListGenerated.onFilterBar().iCheckSearchField(undefined);
        // });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            // When.onThePoPrintListGenerated.onTable(defaultTableId).iPressAction("预览");
            Then.onThePoPrintListGenerated.onTable(defaultTableId).iCheckAction("预览", { enabled: false });
            // When.onThePoPrintListGenerated.onTable(defaultTableId).iPressAction("打印");
            Then.onThePoPrintListGenerated.onTable(defaultTableId).iCheckAction("打印", { enabled: false });
            Then.onThePoPrintListGenerated.onTable(defaultTableId).iCheckColumns(undefined, {"log":{"header":"已打印"},"previewtxt":{"header":"预览PDF"},"ebeln":{"header":"采购订单"},"bukrs":{"header":"公司代码"},"butxt":{"header":"公司名称"},"lifnr":{"header":"供应商"},"name1":{"header":"供应商名称"},"bedat":{"header":"订单日期"}});
        });

        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            When.onThePoPrintListGenerated.onFilterBar().iExecuteSearch();
            Then.onThePoPrintListGenerated.onTable(defaultTableId).iCheckRows();
            When.onThePoPrintListGenerated.onTable(defaultTableId).iPressRow(0);
            Then.onThePoPrintObjectPageGenerated.iSeeThisPage();
        });

        opaTest("Teardown", function (Given, When, Then) {
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});