CLASS zbp_ce_mm_r002 DEFINITION
  PUBLIC
  ABSTRACT
  FINAL
  FOR BEHAVIOR OF zce_mm_r002.

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.

CLASS zbp_ce_mm_r002 IMPLEMENTATION.
ENDCLASS.
